### ISSUE TITLE
Start the editor

### ISSUE THREAD

**Issue by RomanMenzel** [tylerneylon/ed2#1]
where can i get readline?

**Comment by tylerneylon** [comment]
The editor is not yet very useful, since you can't save files yet! See [plan.md](https://github.com/tylerneylon/ed2/blob/master/plan.md) for a list of implemented features.

My mac has `readline` already installed, and I'm not sure how I got it. It may have come with my laptop, or with a developer tool download from Apple (perhaps with Xcode). One way to directly install `readline` is via `brew install readline` using [homebrew](https://github.com/Homebrew/homebrew). I have not personally followed the instructions on [this page](http://stackoverflow.com/questions/7214374/how-do-i-link-against-the-gnu-readline-library-rather-than-libedit-in-macosx), but they may be useful if you want to use the GNU version of `readline`.

**Comment by RomanMenzel** [comment]
But I am using Ubuntu (so Linux).

**Comment by tylerneylon** [comment]
You can install `readline` on ubuntu by running this shell command:

```
sudo apt-get install libreadline6 libreadline6-dev
```

Also, I just did a quick test and found that `ed2` compiles and runs fine on ubuntu. I'm a bit surprised - in a good way! - because I've just been coding on my mac so far.

I'm hoping this will be enough to get you up and running. I'm closing this issue for now, but feel free to ask another question if you have one!

**Comment by RomanMenzel** [comment]
Ok, thank you.
